"$schema" = "https://starship.rs/config-schema.json"

format = """
[](fg:red inverted)$shell[](fg:prev_bg bg:yellow)$username[](fg:prev_bg bg:blue)$git_branch$directory$jobs$status$character
"""
right_format = ''

add_newline = false

[shell]
disabled = false

bash_indicator = "bash"
fish_indicator = "fish"
zsh_indicator  = "Zsh"
powershell_indicator = "PS"
format = '[$indicator](bg:prev_fg)'

[username]
show_always = true
style_user = "bg:prev_bg"
format = '[$user]($style)'

[git_branch]
format = '[$symbol](bg:prev_bg)[$branch](bg:prev_bg)[/](bg:prev_bg)'
symbol = ''
style = 'bg:prev_bg'

[directory]
use_os_path_sep = false
truncation_length = 4
#truncation_symbol = "…/"
style = 'bg:prev_bg'
read_only = ' 󱚮'
read_only_style = 'bg:blue fg:#ff3366'
format = '[$path]($style)[$read_only]($read_only_style)'
[directory.substitutions]
"Downloads" = ""

[jobs]
symbol = '󱫩 '
style = 'bg:prev_bg'
format = '[ $symbol$number]($style)'

[status]
disabled = false
style = 'bg:red fg:#ffccaa'
map_symbol = true

not_found_symbol = ''
not_executable_symbol = ''
sigint_symbol = ''
signal_symbol = ''
symbol = ''

format = '[ ](bg:prev_bg)[](bg:red fg:prev_bg)[$symbol( $maybe_int) ]($style)'

[character]
format = '$symbol '
success_symbol = '[ ](fg:green bg:prev_bg)[](fg:bold green)'
error_symbol = '[](fg:bold red)'
