"$schema" = "https://starship.rs/config-schema.json"

format = '$shell$username$git_branch$directory$jobs$status$character'
right_format = ''

add_newline = false

[shell]
disabled = false

bash_indicator = "bash"
fish_indicator = "fish"
zsh_indicator  = "Zsh"
powershell_indicator = "PS"
style = "bg:#DA627D fg:#ffffff"
format = '[](#DA627D inverted)[$indicator]($style)[](fg:#DA627D bg:#9A348E)'

[username]
show_always = true
style_user = "bg:#9A348E fg:#ffffff"
format = '[$user]($style)[](bg:#9A348E fg:#06969A)'

[git_branch]
format = '[$symbol$branch(:$remote_branch)/]($style)'
symbol = ''
style = 'bg:#06969A fg:bold fg:#F34F29'

[directory]
use_os_path_sep = false
truncation_length = 4
#truncation_symbol = "…/"
style = 'bg:#06969A fg:bold #ffffff'
read_only = ' 󱚮'
read_only_style = 'bg:#06969A fg:#ff3366'
format = '[$path]($style)[$read_only]($read_only_style)'
[directory.substitutions]
"Downloads" = ""

[jobs]
symbol = '󱫩 '
style = 'bg:#06969A fg:bold fg:#ffffff'
format = '[ $symbol$number]($style)'

[status]
disabled = false
style = 'bg:red fg:#ffccaa'
map_symbol = true

not_found_symbol = ''
not_executable_symbol = ''
sigint_symbol = ''
signal_symbol = ''
symbol = ''

format = '[ ](bg:#06969A)[](bg:red fg:#06969A fg:bold)[$symbol$maybe_int ]($style)'

[character]
format = '$symbol '
success_symbol = '[ ](fg:bold fg:green bg:#06969A)[](fg:bold green)'
error_symbol = '[](fg:bold red)'
